### ISSUE TITLE
command failed when app packaged with asar true in electron

### ISSUE THREAD

**Issue by ShijiSun** [ironSource/node-regedit#52]
Command failed: cscript.exe //Nologo C:\Program Files\anna\resources\app.asar\main\lib
etwork\win32\node\vbs\regList.wsf A HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections

Error: Command failed: 
cscript.exe //Nologo C:\Program Files\anna\resources\app.asar\main\lib\network\win32\node\vbs\regList.wsf A HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\Connections at ChildProcess.exithandler (child_process.js:217:12) 
at emitTwo (events.js:106:13) 
at ChildProcess.emit (events.js:194:7) 
at maybeClose (internal/child_process.js:899:16) 
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) killed: false, code: 1, signal: null, cmd: 'cscript.exe //Nologo C:\\Program Files\\anna\\resources\\app.asar\\main\\lib\\network\\win32\\node\\vbs\\regList.wsf A HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Connections

**Comment by muminasaad** [comment]
Check Pull Request to fix this issue  #47

**Comment by kessler** [comment]
fixed in e41c9a88af6c5addb5bf08995f74482774084ae5

**Comment by websrookie** [comment]
目前还是存在这个问题

**Comment by kessler** [comment]
@websrookie 
提供例子 please :)
